server:
  port: 8999
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-service
  messages:
    encoding: UTF-8
    basename: i18n/messages_common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-0.mysql.mysql.svc.cluster.local:3306/sys-threec?useSSL=false&serverTimezone=UTC
    username: root
    password: MSStarForever*00
logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    b-crypt-password-encoder:
      strength: 11